version: "2"
services:
  front:
    build:
      context: .
      dockerfile: "Dockerfile.front"
    environment:
      APP_SHORTNAME: 'tchat-front'
      APP_API_URL: 'http://back:8081'
    volumes:
     - ./dist:/usr/share/nginx/html
    ports:
    - "9000:80"
    links:
    - back
  back:
    build:
      context: .
      dockerfile: "Dockerfile.back"
    volumes:
     - ./server:/app
    ports:
    - "8081:8081"
networks:
  default:
    external:
      name: dockernet
