FROM nginx

COPY dist /usr/share/nginx/html
COPY nginx.tmpl /etc/nginx/nginx.tmpl

CMD /bin/sh -c "envsubst '\$APP_SHORTNAME \$APP_API_URL' < /etc/nginx/nginx.tmpl > /etc/nginx/nginx.conf && nginx -g 'daemon off;' || cat /etc/nginx/nginx.conf"
